**Numpy**

* Numpy -> numerical Python

pip install numpy -> Kurulum için

In [1]:
import numpy as np

Numpy ndarray nesnesi

In [2]:
nd = np.array([1,2,3,4,5,6,7])

print(nd)

[1 2 3 4 5 6 7]


In [3]:
print(type(nd))

<class 'numpy.ndarray'>


In [4]:
nd = np.array((1,2,3,4,5,6,7))

print(nd)

[1 2 3 4 5 6 7]


Dizilerde Boyutlar

In [5]:
# 0-Boyut
nd = np.array(35)

print(nd)

35


In [6]:
# 1-Boyut
nd = np.array([1,2,3])

print(nd)

[1 2 3]


In [7]:
# 2-Boyut
nd_2 = np.array([[1,2,3], [4,5,6]])

print(nd_2)

[[1 2 3]
 [4 5 6]]


In [9]:
# 3-Boyut
nd_3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [11,10,12]]])

print(nd_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 10 12]]]


In [11]:
#Dizinin boyutunu alma -> ndim

print(nd_3.ndim)
print(nd_2.ndim)

3
2


In [12]:
#çok boyutlu diziler

nd = np.array([1,2,3], ndmin=2)

print(nd)
print(nd.ndim)

[[1 2 3]]
2


In [14]:
#dizinin satır ve sütun bilgilerini alma -> shape
nd = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [11,10,12]]])

print(nd.shape)

(2, 2, 3)


In [15]:
#dizinin satır ve sütun değerlerini değiştirme -> reshape
nd = np.array([1,2,3,4,5,6,7,8,9,0])

print(nd.shape)

(10,)


In [17]:
print(nd.reshape(5, 2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
[1 2 3 4 5 6 7 8 9 0]


In [18]:
#arange()
nd = np.arange(0, 10, 2)

print(nd)

[0 2 4 6 8]


In [20]:
#Dizi elemanlarına erişim
nd = np.array([1,2,3,4,5])

print(nd[2])

3


In [23]:
nd_2 = np.array([[1,2,3], [4,5,6]])

print(nd_2[1, 2])
print(nd_2[0, -1])

6
3


In [24]:
nd = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

print(nd)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [25]:
print(nd[0, 1, 2])

6


In [27]:
#numpy slicing

nd = np.array([1,2,3,4,5,6,7,8])
print(nd[:4])

[1 2 3 4]


In [28]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.random.random((2, 3))

array([[0.77747946, 0.6802901 , 0.24305573],
       [0.44458769, 0.87656948, 0.96146649]])

In [33]:
np.linspace(4, 5, num=5)

array([4.  , 4.25, 4.5 , 4.75, 5.  ])

In [34]:
np.linspace(4, 5, 5, endpoint=False)

array([4. , 4.2, 4.4, 4.6, 4.8])

In [36]:
np.full((2,3), 8)

array([[8, 8, 8],
       [8, 8, 8]])

In [37]:
#matrisleri birleştirmek
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])

nd3 = np.concatenate([nd1, nd2])
print(nd3)

[1 2 3 4 5 6]


In [38]:
my_list = [1,2,3]
nd2 = np.array([4,5,6])

nd3 = np.concatenate([my_list, nd2])
print(nd3)

[1 2 3 4 5 6]
